stages:
  - lint
  - train_model
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: mlops_app
  DOCKER_IMAGE_TAG: latest

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - dvc pull

lint:
  stage: lint
  script:
    - black --check src tests
    - mypy src tests

train_model:
  stage: train_model
  script:
    - python -m src.services.model_pipeline.pipeline
  artifacts:
    paths:
      - models/

test:
  stage: test
  script:
    - pytest tests/

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Pushing image to DockerHub/GitLab Registry..."
    # docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    # docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    # docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG