stages:
  - train_model
  - lint
  - test
  - build

variables:
  DOCKER_IMAGE_NAME: mlops_app
  DOCKER_IMAGE_TAG: latest

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - dvc pull

train_model:
  stage: train_model
  script:
    - python -m src.services.model_pipeline.train_model
  artifacts:
    paths:
      - models/

lint:
  stage: lint
  script:
    - black --check src tests
    - mypy src tests

test:
  stage: test
  script:
    - pytest tests

# data_quality:
#   stage: test
#   script:
#     - great_expectations checkpoint run <checkpoint_name>

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push registry.gitlab.com/msrbl-group/MLOps_team21/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
